void Draw_UserCheatsMenu_Ani(menu_list_t * list);
void Draw_UserCheatsMenu(menu_list_t * list);
void Draw_CheatsMenu_Selection_Ani();
void Draw_CheatsMenu_Selection(int menuSel, u32 rgba);
void Draw_CheatsMenu_View_Ani_Exit(void);
void Draw_CheatsMenu_View_Ani(const char* title);
void Draw_CheatsMenu_View(const char* title);
void Draw_CheatsMenu_Options_Ani_Exit(void);
void Draw_CheatsMenu_Options_Ani(void);
void Draw_CheatsMenu_Options(void);
void Draw_OnlineYearsMenu(menu_list_t * list, int total);
